# Generated by Django 5.2.6 on 2025-09-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
